# Generated by Django 3.0.7 on 2020-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
